CREATE TABLE IF NOT EXISTS agent_run (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    bad_case_id BIGINT DEFAULT NULL COMMENT 'nullable until ai_bad_case is introduced',
    experiment_arm VARCHAR(32) NOT NULL,
    status VARCHAR(32) NOT NULL,
    max_steps INT NOT NULL,
    max_model_calls INT NOT NULL,
    max_total_tokens INT NOT NULL,
    timeout_ms BIGINT NOT NULL,
    used_steps INT NOT NULL DEFAULT 0,
    used_model_calls INT NOT NULL DEFAULT 0,
    used_prompt_tokens INT NOT NULL DEFAULT 0,
    used_completion_tokens INT NOT NULL DEFAULT 0,
    used_total_tokens INT NOT NULL DEFAULT 0,
    result_summary TEXT DEFAULT NULL,
    error_code VARCHAR(64) DEFAULT NULL,
    error_message VARCHAR(500) DEFAULT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    started_at DATETIME NOT NULL,
    deadline_at DATETIME NOT NULL,
    completed_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uk_agent_run_user_idempotency (user_id, idempotency_key),
    INDEX idx_agent_run_user_status_created (user_id, status, created_at),
    INDEX idx_agent_run_bad_case (bad_case_id),
    CONSTRAINT fk_agent_run_user FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agent_step (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    run_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    sequence_no INT NOT NULL,
    role_name VARCHAR(32) NOT NULL,
    step_type VARCHAR(32) NOT NULL,
    tool_name VARCHAR(64) DEFAULT NULL,
    status VARCHAR(32) NOT NULL,
    input_summary TEXT DEFAULT NULL,
    output_summary TEXT DEFAULT NULL,
    prompt_tokens INT NOT NULL DEFAULT 0,
    completion_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    elapsed_ms BIGINT NOT NULL DEFAULT 0,
    error_code VARCHAR(64) DEFAULT NULL,
    error_message VARCHAR(500) DEFAULT NULL,
    started_at DATETIME NOT NULL,
    completed_at DATETIME DEFAULT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uk_agent_step_run_sequence (run_id, sequence_no),
    INDEX idx_agent_step_user_run (user_id, run_id),
    CONSTRAINT fk_agent_step_run FOREIGN KEY (run_id) REFERENCES agent_run(id) ON DELETE CASCADE,
    CONSTRAINT fk_agent_step_user FOREIGN KEY (user_id) REFERENCES user_account(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
